#badger
#use when web browsers aren't working(DNS issue)("can't connect to server").
#file has "nameserver ::1" when broken.
file="/etc/resolv.conf" #network manager generated .conf file.
google_ip_addr="8.8.8.8" #google ip to search on web.

echo "# Generated by NetworkManager\nnameserver ${google_ip_addr}">$file